/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * DTCM:     #  .data  #  .bss  #  (small spare)  #  MSP stack  #
 * AXI SRAM: #  .dma_buffer  #  .axi_heap  <- newlib heap grows here  #
 * @endverbatim
 *
 * The heap starts at '_axi_heap_start' and ends at '_axi_heap_end' (the size is set by
 * '_Axi_Heap_Size' in the linker script).
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  /* PurrMidi: the newlib heap lives in its own .axi_heap section (AXI SRAM, see the linker
   * script) instead of the DTCM space left after .bss. DTCM had only ~20 KB free, while
   * TinySoundFont needs ~170 KB for the SoundFont preset tables. */
  extern uint8_t _axi_heap_start; /* Symbols defined in the linker script */
  extern uint8_t _axi_heap_end;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_axi_heap_start;
  }

  /* Never grow past the end of the heap section */
  if (incr > (ptrdiff_t)(&_axi_heap_end - __sbrk_heap_end))
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif
